---
# README
#
# This does not contain the listen directives. These are varied based on how the vault server is being executed:
# - The bootstrap job only listens over HTTP localhost
# - The production deployment only listens over HTTPS on all interfaces
#
# This is so we can use vault servers PKI backend to generate the SSL certifices vault clients will later use
# to connect to it.
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vault-config"
  namespace: {{ default "default" .Values.namespace }}
data:
  # The URL suffix (.cluster.local) of the Kubernetes service URLs is configurable. The search configuration in the resolv.conf
  # injected into this pod should resolve this domain correctly, no matter the .cluster.local
  config.json: |
    {
      "backend": {
        "etcd" {
          "address": "vault-etcd.{{ default "default" .Values.namespace }}".svc"
        }
      }
    }

