---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "secret-management"
  namespace: {{ default "default" .Values.namespace | quote }}
  labels:
    application: "vault"
    role: "secret-management"
spec:
  selector:
    application: "vault"
    role: "secret-management"
  ports:
    - protocol: "TCP"
      name: "http"
      port: 8200
  type: {{ default "ClusterIP" .Values.serviceType | quote }}
