---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: {{ template "linkerd-ingress.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd-ingress.fullname" . }}
data:
  # Todo: Optionally enable telemetry output. Prometheus should collect this
  # Todo: Optionally enable trace output. No use for this yet, but it's a cool idea.
  config.yaml: |-
    admin:
      port: 9990
    namers:
    - kind: io.l5d.k8s
    routers:
    - protocol: http
      identifier:
        kind: io.l5d.http.ingress
      servers:
        - port: 80
          ip: 0.0.0.0
          clearContext: true
      dtab: /svc => /#/io.l5d.k8s
    usage:
      orgId: linkerd-examples-ingress 
