---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
  labels:
    app: {{ template "linkerd-ingress.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd-ingress.fullname" . }}
spec:
  selector:
    app: {{ template "linkerd-ingress.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - protocol: "TCP"
      name: "http"
      port: 80
    - protocol: "TCP"
      name: "https"
      port: 443
  type: {{ default "LoadBalancer" .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}}
  {{ if .Values.service.loadBalancer.publicIp -}}
  loadBalancerIP: {{ .Values.service.loadBalancer.publicIp }}
  {{ if .Values.service.loadBalancer.allowedIps -}}
  loadBalancerSourceRanges:
{{ .Values.service.loadBalancer.allowedIps | toYaml | indent 4 }}
  {{ end -}}
  {{ end -}}
  {{ end -}}
