---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
data:
  foo: |-
    {{ .Files.Get "foo.xml" | b64enc | quote}}
  bar: {{ .Values.bar | b64enc | quote }}
