---
name: "linkerd-ingress"
## The version should track the upstream version, followed by the iteration. This follows the pattern established by the
## Debian package version.
## See https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version
version: "0.9.1-1"
description: "Provides linkerd as a Kubernetes Ingress controller"
keywords:
  - "Linkerd"
  - "Ingress"
home: "https://github.com/kubernetes/charts"
sources:
  - "https://github.com/kubernetes/charts/stable/linkerd-ingress"
maintainers:
  - name: "Andrew Howden"
    email: "hello@andrewhowden.com"
engine: gotpl
icon: "__LOGO_URL__"
